### ISSUE TITLE
Accounts & wallets interaction

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/heroes#10]
Right now 1 account can switch between multiple wallets and vice versa, one wallet can be connected with multiple accounts. This is not OK at all, we should allow 1 account to be linked with 1 wallet address only.
<img width="200" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/5b8726ed-7c15-4347-a443-4159a00b331c"> <img width="200" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/0a9c1bc8-13cb-4345-b9b0-f7f9805392f4">

**Comment by cudam321** [comment]
Additionally, I can edit or cancel a bounty of a profile with another profile as long as they're connected to the same wallet. 

<img width="1297" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/afd5265f-704e-47d5-b859-eefc71112f79">
<img width="1297" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/b68cb41b-2570-4a48-9216-ad729fe409f2">

**Comment by AngelBlock** [comment]
New flow is as follows:
- user signs out - it disconnects the wallet automatically.
- user login again and will have to connect the wallet again.
- user can login with another wallet, but all data like KYC, bounties, reputation etc
