### ISSUE TITLE
Remember Me not working during login.

### ISSUE THREAD

**Issue by mohdabbas561** [HeroesHQ/HEROES#103]
Hey, i guess remember me is not working pretty well, when u login and tick on remember me and go to dashboard, as soon as i close the browser, it again asks for relogin and again i hv to re enter email and password both. Remember me should keep user logged in if not atleast it must keep the, email prefiled.

**Comment by AngelBlock** [comment]
Remember me is deprecated and will be removed in coming release. All the sessions will be "remembered" but default.
