### ISSUE TITLE
Emails for same action keeps coming out every day at 13.00 CET

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#104]
**Describe the bug**

I keep getting reminders for each email action, this becomes alot

**Expected behavior**

One email per action, no reminders for users not taking a specific action

**Screenshots**

Example of an email that keeps coming every day at the same time from stag env

<img width="359" alt="Screenshot 2023-11-20 at 17 56 35" src="https://github.com/HeroesHQ/HEROES/assets/18598519/70b2732f-0ace-4f0a-9255-707ae7d945a6">

**Comment by AngelBlock** [comment]
Current setup:

Subject: Reminder: Activity on Your Bounty Awaits Your Response
**Sent once a day at 12:00,** until the user performs the expected action.

Urgent: Your Bounty "${bountyTitle}" is Nearing Its Deadline
**Begins to be sent every day, 3 days before the deadline**. It is not sent if the deadline has passed, or if the user has performed the action.


Please remove these and other repeating email notifications

@Kisgus @fedencer @starpause
