### ISSUE TITLE
Import from Github displays in markdown format - which other options for Github integration?

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#106]
**Describe the bug**

Github import feature is not importing bounty

**To Reproduce**

Create bounty, insert github issue URL

**Expected behavior**

Import Title and description of Github issue markdown

**Screenshots**

<img width="1469" alt="Screenshot 2023-11-22 at 10 21 27" src="https://github.com/HeroesHQ/HEROES/assets/18598519/c242bb27-cbba-4c1a-bcc1-f9f9490a98f3">

**Desktop (please complete the following information):**
Macbook

**Comment by cudam321** [comment]
works fine for me, i don't think the link you put in the field is a link to an issue

<img width="1678" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/f1104030-e58e-4d12-96d9-0ff982a4a22b">

**Comment by Kisgus** [comment]
Thanks @cudam321, I changed issue to markdown now.

<img width="689" alt="Screenshot 2023-11-22 at 11 42 49" src="https://github.com/HeroesHQ/HEROES/assets/18598519/c810c99b-c8ee-4fc2-8055-7036368dfc0e">

Can we easily fix markdown, or which other import options for heroes exist @AngelBlock ?

**Comment by AngelBlock** [comment]
@Kisgus can you advise what do you suggest to change ser?
