### ISSUE TITLE
[WORK REQUEST] Hunter claiming v2 "fast track"

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#109]
🤼‍♂️  What problem is your work solving.**

I wish to make it easier for hunter to claim bounty by removing steps & clicks

🎉  Describe the work you'd like

a) Funder puts up bounty (can be single payout or multiple payout), also specific whitelist restrictions may apply
b) Eligible Hunter for bounty (if no whitelist restrictions all hunters) submits work
c) Funder review work, if all good press "done" and funds are released + invoice generated

This means to change:

- [x] Do not have deadline to timeout bounty
- [x] Remove bond paid by hunter
- [x] Allow hunter to "start work" & "submit work" in one action so that they only have to take this one action

## 🔗  Work doc(s) / inspirational links

Add design file when ready

**Comment by starpause** [comment]
+1 high friction point, is it possible to set up a bounty with auto approve & then when the hunter is submitting work in the UI, send smart contract calls for both claim and submit?

**Comment by AngelBlock** [comment]
Issue 109 is a simplified version of the bounty, in the UI we only put the option when creating a bounty "Simple bounty flow"?

Should the same option be used for 144 "NEWS Submission", but here we need another option - "Claimer can create multiple claims simultaneously"?

Is this okay? Just add two new options in the creation process?
Or should we create a "Add News" button somewhere, for example?


**So general UX/UI clarification required**. please advise.
