### ISSUE TITLE
Invoice template overhaul suggestion 

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/heroes#11]
<img width="500" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/be733345-507d-44f7-8be5-2b8d74f982d7">

Suggestion:
- Remove the line at the bottom - unnecessary & confusing
- The pfp is unnecessary
- Change "Total of 240 hours at USDT.e" to something else - confusing

overhaul example
[example invoice.pdf](https://github.com/HeroesHQ/heroes/files/11519658/example.invoice.pdf)

**Comment by Kisgus** [comment]
Assigning myself, next step is to get final requirements for accountant / customers

**Comment by P3ter-NEARWEEK** [comment]
**HEROES VAT feedback from Fidura**

- For NEARWEEK/HEROES the only thing that matters is whether the bounty poster is registered in Switzerland or not.

- If the bounty poster is registered in Switzerland, we need to add HEROES/NEARWEEK VAT to the 10% tx fee as this is considered income.

- If the bounty poster is registered outside Switzerland, no VAT on the 10% tx fee is needed

**VAT between bounty poster and bounty taker**

Entity <> Entity
- Scenario: A Swiss registered entity posts a bounty and a Swiss entity takes the bounty = 7.7% VAT needs to be added.

Entity <> Freelancer
- Scenario: A Swiss registered entity posts a bounty and a Swiss citizen / freelancer takes the bounty = VAT needs to be added to the invoice if that freelancer is VAT registered, if not no VAT shall be added to the invoice.


**Email from Claudio:**

The invoice does look fine. The point about the VAT we discussed must be somehow implemented.

And I'm not only talking about the Swiss VAT. It could also be, that a guy in Japan does offer some services to someone in Germany.
Then the turnover is done in Japan but for an abroad people. I don´t know if and how the Japan VAT will be applicable. When you will provide invoices for the user of the platform, this must be somehow known or delegated...

And what how is the VAT, when the Japan guy is providing services to a Japan company...?!
