### ISSUE TITLE
Change "edit deadline" to display the same as in the bounty creation flow

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#111]
## Journey / Reproduce
If bounty funder wants to edit the deadline of their bounty, the old display is showing instead of the new one

<img width="394" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/cd70be72-cf7d-4149-8100-b4b38645bf86">

## Suggestion/Solution
Change it to be identical to the new deadline selection display
<img width="618" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/217943b8-6199-4ef5-b87c-1a849ba55406">

**Comment by Kisgus** [comment]
Cancelling, please reopen new issue for new funder flow @cudam321
