### ISSUE TITLE
Can't create bounty on test server

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#112]
🔎 Describe the bug

Cannot create bounties on test with any token or any configuration

## 🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:
- create bounty on test

## 🎉 Expected behaviour
The app returning this screen
<img width="1674" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/a6c2d74e-56b4-4b20-9ac4-fc6c42ac8b27">

##  🖥 Device info 
 - Browser [e.g. Arc, Edge]
 - Version [e.g. -]

## 🔗  Screenshots/ Additional material
Txns of the failed bounties:
https://testnet.nearblocks.io/txns/EXuK6KbrBfKue5DqCR2r25VjbDEsJCWwGqs4XN7pEetY
https://testnet.nearblocks.io/txns/HuTyNHLEQNDg4vrjVdidoeFgtUqkHiEgmCqhAjQnhh5Z
https://testnet.nearblocks.io/txns/49mhKPLKgbSijgPy8ZTeiktCfMGBYNGX7mHrV1Dfe3ot

**Comment by AngelBlock** [comment]
Please test

**Comment by cudam321** [comment]
fixed
