### ISSUE TITLE
Funder cannot accept applicant (NEKO)

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#113]
## 🔎 Describe the bug

- bounty creation txn: https://nearblocks.io/txns/4urNay6uF4xgQSLcKU8ki6aDehai5mmyfDh9zxyBMqh9
- hunter claiming txn: https://nearblocks.io/txns/977r9aevD5V22axihrxw1KLwieoUAyRj73zmzQWwfAC5#execution

**Funder cannot accept the applicant after they have applied to the bounty (The "Accept" button turns gray)**

![telegram-cloud-photo-size-5-6267063992124029204-y](https://github.com/HeroesHQ/HEROES/assets/97611620/6cd655bb-be4a-4792-809b-37eb7e7260d5)

The hunter's application also didn't reflect on the activity log

![telegram-cloud-photo-size-5-6266962209989049263-y](https://github.com/HeroesHQ/HEROES/assets/97611620/86d607c6-5203-404c-989c-f19ac26a4994)

## 🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:

1) Create bounty
2) Add whitelist & reviewer
3) Use NEKO as rewards
4) No KYC, No invoice, No Multitasking, Manual approval

## 🎉 Expected behaviour

-

## 🔗  Screenshots / additional material
From applicant perspective
![telegram-cloud-photo-size-5-6267063992124029207-x](https://github.com/HeroesHQ/HEROES/assets/97611620/8dc4cd01-1547-4983-b436-52d0527a43b9)

**Comment by rostyslav-dzhuman** [comment]
Fixed on prod. Please check.

**Comment by AngelBlock** [comment]
Please test @cudam321
