### ISSUE TITLE
[WORK REQUEST] Submit contest to learn near club

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#115]
🤼‍♂️  **What problem is your work solving.**

Update quiz for LNC

🎉  **Describe the work you'd like**

- [ ] Update quiz
- [ ] Submit to review

**Comment by cudam321** [comment]
done
https://docs.google.com/document/d/10Vl98_mDTj6kfhWUdFlpG62q8y2vI8gcFU427y37Dgw/edit?usp=sharing

**Comment by Kisgus** [comment]
Ty ser
