### ISSUE TITLE
Hunter can skip providing invoice data

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#117]
🔎 Describe the bug

A hunter skipping the profile setup can still claim a bounty with invoice selected

##🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:

1) create a fresh account
2) skip profile setup
3) claim a bounty

##🎉 Expected behaviour
Invoice input fields are not there

## 🖥 Device info 
 - Browser [e.g. Arc, Firefox

##🔗  Screenshots
![telegram-cloud-photo-size-5-6269080462089631254-y](https://github.com/HeroesHQ/HEROES/assets/97611620/92324c05-756c-41d9-8a73-980c6039f311)

**Comment by cudam321** [comment]
proof of invoice
[invoice-23-hgpquynh.near-215-0fccafb0d3724492a02b2fbf49865ec5-1700810947705-31305.pdf](https://github.com/HeroesHQ/HEROES/files/13457216/invoice-23-hgpquynh.near-215-0fccafb0d3724492a02b2fbf49865ec5-1700810947705-31305.pdf)

**Comment by AngelBlock** [comment]
@cudam321 @starpause @Kisgus 
advise sought in terms of how to handle this case @maanemanden 
Should we disable the Done button and instruct user to go and finish the profile?

**Comment by cudam321** [comment]
i think we should prevent this whole thing from the start, meaning disable everything with users that havent finished their profile

**Comment by Kisgus** [comment]
Sounds good to me @cudam321, it is OK to require "completed" profile needed to claim bounty, we need to give clear guidance with this (similiar to how we do with connect wallet now)

**Comment by starpause** [comment]
Design request: what happens if user doesn't have profile filled in?
