### ISSUE TITLE
New Template For All Heroes Emails 

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#118]
🤼‍♂️  **What problem is your work solving.**

Old email style is very plain and not on brand with HEROES BUILD. 

🎉  **Describe the work you'd like**

Create a new email template that is on brand.

## 🔗   Work doc(s) / inspirational links

Use a well tested baseline such as https://github.com/leemunroe/responsive-html-email-template which also provides Figma files to design with.

Template will be sent via our current email service (https://www.zoho.com/zeptomail/) and used across all the email flows we send ([originally specified here](https://github.com/HeroesHQ/HEROES/issues/100)).

**Comment by maanemanden** [comment]
Updated based on figma template here: https://www.figma.com/file/QC7ZOIGywyF6ERd2ERGfj4/htmlemail-templates?type=design&node-id=0%3A248&mode=design&t=zPB2EuWvQY7QBDml-1
