### ISSUE TITLE
Bounty Creation: Enhance Navigation Clarity

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#119]
Enhance Navigation Clarity in Bounty Creation Flow with Interactive Step Indicators and Unique URLs.

## 🤼‍♂️  **What problem is your work solving.**

![image](https://github.com/HeroesHQ/HEROES/assets/408953/3db8ce9c-5222-4278-a926-06d7985ce51e)

- When creating a bounty, the steps are not clearly indicated, causing confusion about the process flow.
- The current step indicator is not interactive, which could provide a more intuitive navigation experience.
- The inability to jump directly into a specific step of the bounty creation hinders both user accessibility and tracking capabilities.
- Discrepancies exist between the old step component, which includes five steps, and the new design, which has been streamlined to four steps. This requires alignment with the [Funder Bounty Creation milestone](https://github.com/HeroesHQ/HEROES/milestone/2).

## 🎉  **Describe the work you'd like**

- [ ] Introduce labels for the step indicator dots and ensure the dots are in this order (a different order than designs): 
  - Details
  - Payment
  - Access (was Approval)
  - Review
- [ ] Make the indicator dots clickable to enhance navigation alongside the existing back/next buttons.
- [ ] If the user tries to navigate away from a screen with required fields missing (using the nav dots or bottom navigation buttons), do not load the next page. Instead highlight the missing field and scroll the user to it.
- [ ] Integrate Mixpanel analytics to trigger page view events for each step in the Create Bounty workflow.

## 🔗   Work doc(s) / inspirational links

- Final designs to be attached upon completion.
- [Wireframes](https://www.figma.com/file/KiEyqiJBRt9e2rX56T14uw/Bounty-Creation-Wireframe?type=whiteboard&node-id=202%3A630&t=IPW0ZlcWrPlSz05X-1)

**Comment by starpause** [comment]
Some justification for the order of steps:

The steps to create a bounty should be ordered logically to follow the natural progression of creating and posting a bounty. Here is a suggested order with explanations for why they are arranged as such:

Details: This is where the bounty creator specifies what the job entails. Providing details first ensures that potential bounty hunters understand what is expected before considering the payment or other terms.

Payment: Once the details are clear, the next logical step is to define the payment. This would include setting the bounty amount, currency (if applicable), and payment terms. This step solidifies the commitment of the bounty poster to the task.

Access: After the details and payment are set, the approval process typically involves reviewing the terms of the bounty, any legal considerations, and compliance with platform policies. This step may also include internal approvals if the bounty is posted by a team or organization.

Review: The final step before publishing the bounty should be a review, where the bounty creator can check all entered information, edit if necessary, and confirm that all the information is accurate and complete.

Presenting the steps in this order helps ensure that the creator of the bounty has provided all the necessary information and agreed to the terms before the bounty goes live, minimizing the need for revisions or clarifications later on. This sequence also reflects a natural workflow, which can help in making the process intuitive for users.

**Comment by starpause** [comment]
Justification of Access instead of Approval:

The "Approval" step name might be confusing, as it implies either a third-party or administrative approval OR a self-check by the user. In reality, the step is about controlling who can participate in the bounty.

**Access:** This indicates that the bounty creator is controlling who has access to the bounty, both for claiming work and approving work.

**Comment by Kisgus** [comment]
Ready @rostyslav-dzhuman is it ready for review?
