### ISSUE TITLE
Edit Bounty Bug

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/heroes#12]
The bounty Category & Experience Level didn't change after being edited

<img width="863" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/dfd5d6b5-74d8-4118-8332-65b15cf203d8">

In the beginning it was "Development" & "Beginner", changed to "Other" & "Advanced" but UI didn't update.

https://explorer.near.org/transactions/3HhFeN6WtB99v4aqrpSx3ijN3TXzRwN2tKjkK4KjYmiP

**Comment by cudam321** [comment]
Update: UI updated after cancelled

**Comment by AngelBlock** [comment]
New flow is live so not relevant any more.
