### ISSUE TITLE
Redesign Tag Input Component for Enhanced Usability

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#121]
## 🤼‍♂️  **What problem is your work solving.**

![image](https://github.com/HeroesHQ/HEROES/assets/408953/35457319-86f3-4822-be8b-92724cfc181d)

The current tag input component in our application combines a select dropdown with a tag selector, a design that is uncommon and has proven to be confusing for our users. This unconventional approach causes uncertainty in interaction, as users are not familiar with this type of interface in a tag selection context. The goal is to redesign this component to behave like a standard tag select, which is more intuitive and aligns with common practices in modern web interfaces.

Key Issues with Current Design:

- Combining select dropdown with tag selector leads to user confusion.
- When users attempt to add a tag not in the preset list, they receive a "default" tag, which is invalid.
- Limitation to only accept tags that are in the smart contract restricts user ability to fully describe their bounty.
- The select dropdown opens upon clicking "Tags" text input or pressing the arrow, adding to the complexity.

## 🎉  **Describe the work you'd like**

The tag input should allow users to type and select multiple tags. As users type, the component should suggest available tags (autocomplete feature). Selected tags should be displayed as individual "chips" or "bubbles" within the input field. Users should be able to remove a selected tag with a simple click or tap. Consider accessibility and responsive design in the new implementation.

- [ ] Remove the select drop down
- [ ] Adopt standard tag autocomplete UI/UX 
  - Follow UI pattern similar to [this Angular example](https://codepen.io/webmatze/pen/DQVdWr).
  - Placeholder text should be "add a tag".
  - Autocomplete feature: Suggest tags from our smart contract as users type. If no matches are found, user can hit enter to create a tag that will be used in Heroes frontend/backend but won't be part of the smart contract.
  - Avoid duplicate tags: If a user tries to add a tag that's already selected, highlight the existing tag instead of adding a duplicate.
- [ ] Add tags from previous drop downs
  - Marketing
  - Development
  - Other
  - Content
  - Beginner
  - Intermediate
  - Advanced
  - Any
- Add tags from hirevibes.com
  - Engineering
  - Management
  - Sales
  - Support
- [ ] Allow any tags to be used
  - Highlight pre-populated tags from the smart contract differently from user-added tags to distinguish them.
  - Implement analytics to track user-input tags for potential inclusion in the smart contract in future updates.
- [ ] Accessibility features: Ensure the component is navigable via keyboard and readable by screen readers.
- [ ] Technical Requirements: The component should be responsive and compatible across different browsers.

## 🔗   Work doc(s) / inspirational links

- [uxcel description of input tags](https://app.uxcel.com/lessons/anatomy-694#input-tag-4763)
- [codepen search for input tag examples](https://codepen.io/search/pens?q=input+tag)

**Comment by maanemanden** [comment]
added to proto @starpause
