### ISSUE TITLE
[WORK REQUEST] Clarify bountys' status & interaction when hunter's work is rejected

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#122]
### Context: 
Currently, all HEROES bounties can only accept the number of hunters that match the preset payout slot even if their works are rejected.

Example: Normal bounty for 1 hunter, 1 payout
- Funder created a bounty
- A hunter apply & start work
- Hunter's work got rejected
=> Funds are still in escrow, bounty still said "CLAIMED" and no one else can apply to it, while technically it's still open

Example: Multi payout bounty
- This bounty has 5 slots: https://heroes.build/bounties/bounty/154
- 5 hunters applied & started work
- 3 got rejected
=> Part of the funds is still in escrow, but no one else can apply to it, while technically it's still open

## 🎉  **Describe the work you'd like**

- [ ] Allow others to apply to a bounty when previous hunter(s) of that bounty gets rejected
- [ ] Bounty returns to "NEW" state if hunter(s) of that bounty gets rejected and no one is actively working on it

**Comment by starpause** [comment]
As a user, whether a funder or a hunter, my expectation is that when a hunter is rejected from a task or bounty, the slot they previously occupied becomes available again for other hunters to claim. 

@AngelBlock Is it currently possible to mark a bounty as completed even if there are outstanding, unpaid payouts? 

@AngelBlock When the bounty is marked as complete/finished, what currently happens to the unpaid escrowed funds that are held by heroes?

**Comment by Kisgus** [comment]
Hey @cudam321 is this still relevant?

**Comment by cudam321** [comment]
@Kisgus it's not, there is a grace period, once a bounty passed the period funder can update bounty status & start accepting new hunters or cancel the bounty.
