### ISSUE TITLE
[WORK REQUEST] HEROES Telegram bot

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#126]
🤼‍♂️  **What problem is your work solving.**

I wish to enable users on Telegram to be able to see when a new bounty is live and have a link to click to view it

🎉  **Describe the work you'd like**

- [ ] Telegram bot is added to a channel
- [ ] When the bot is added (or before) the person adding it can choose which bounty types (based on tags) that the bot should post
- [ ] The Telegram bot now posts when a new bounty has been made
- [ ] A user seeing this can click (to heroes.build) UI to claim bounty

**Comment by starpause** [comment]
If external developer: can it be open source and part of delivery is to implement it on a telegram account/api key owned by HEROES.

**Comment by cudam321** [comment]
test bot based on staging bounties: https://t.me/herobountybotchanneltest
