### ISSUE TITLE
Develop Shell Script for Automated Testing of Smart Contracts on heroes.build

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#127]
Note: this is at the research phase we are looking to scope the effort to set up this kind of automated testing. That way we can weigh it's cost against it's benefits compared to other testing strategies. 

## 🤼‍♂️  **What problem is your work solving.**

We need a shell script to automate the testing of various smart contract functions in our heroes.build project. This script should interact with our smart contracts using the near-cli npm package (or other, better sdk/cli tools if they exist) and test key functionalities like creating bounties, claiming them, approving workers, submitting work, approving work, and handling payouts.

## 🎉  **Describe the work you'd like**

- The script should be written for a *nix environment (including WSL, OSX, etc.).
- It should use the `near-cli` npm package to interact with the smart contracts.
- The smart contracts are currently closed source and located in the heroes repo.
- The testing script should cover the following functionalities (at a minimum, add other journeys along the way):
  1. **Make Bounty:** Test creating a new bounty.
  2. **Claim Bounty:** Simulate a user or worker claiming an available bounty.
  3. **Approve Worker:** Test the approval process of a worker for a bounty.
  4. **Submit Work:** Check the submission of work by the approved worker.
  5. **Approve Work:** Test the approval process of the submitted work.
  6. **Payouts:** Ensure that payouts are correctly processed upon work approval.

### AI-Assisted Test Cataloging:
- The developer is expected to use AI tools to analyze the project's documentation and codebase.
- This analysis should help in identifying and cataloging the necessary tests comprehensively.
- The goal is to ensure that all relevant functionalities and edge cases are covered by the tests.

### Additional Considerations:
- Research and suggest any available testing frameworks that can be integrated for better testing efficiency.
- The script should include error handling and report back any failures in the testing process.
- It is crucial to ensure that the script is easily modifiable for future updates to the smart contract methods.

### Deliverables:
1. A shell script that automates the testing process for the mentioned functionalities.
2. Documentation/comments within the script explaining each part for easy understanding and maintenance.
3. A brief guide on how to set up and run the script, including setting up any necessary environment variables.
4. A report or documentation of the AI-assisted test cataloging process and its outcomes.

### How to Submit Work:
Please submit a pull request to the `heroes.build` repository with your script, documentation, and AI-assisted test cataloging report. The PR should be adequately documented for review.

**Comment by Tarnadas** [comment]
Why do you want to do this via CLI invocations on Testnet?
You can use [workspaces-rs](https://crates.io/crates/near-workspaces) to run integration tests in a sandbox. Alternatively you can even use workspaces-rs to run the tests on Testnet, but I would not recommend that. It's only needed, if you need to do integration tests including indexer and potentially other off-chain stuff.

You can check out the tests that I wrote for [Protocol Pawns](https://github.com/Protocol-Pawns/chess-on-chain/tree/master/crates/chess-test). I hope they are easy to understand.
