### ISSUE TITLE
Not able to preview invoice 

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#129]
🔎 Describe the bug

I'm not able to 

##🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:

1) Setup bounty with whitelist, KYC, reviewer and pre-approval (this is bounty with one person claiming, not multi-task)
2) Bounty hunter claim and press done
3) When about to release funds I cant see invoice preview

It was for this bounty

https://heroes.build/bounties/bounty/218

##🎉 Expected behaviour

I wanna be able to see invoice preview

## 🖥 Device info 

Macbook / Google Chrome

##🔗  Screenshots

<img width="1470" alt="Screenshot 2023-11-28 at 18 30 56" src="https://github.com/HeroesHQ/HEROES/assets/18598519/8acfee8d-9f97-4643-aa37-d1ea7a7d0f7a">

**Comment by Kisgus** [comment]
Update: Funds have now been released, there are still no invoice to donwload

<img width="1373" alt="Screenshot 2023-11-28 at 18 40 00" src="https://github.com/HeroesHQ/HEROES/assets/18598519/ac5570b4-4617-43a9-815b-39bc9f15b648">

**Comment by fedencer** [comment]
Fixed a bug in displaying the list of accounts for bounty where invoice generation is disabled
