### ISSUE TITLE
[WORK REQUEST] Not able to great bounty on test version when using import github feature (ON TESTNET)

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#131]
🔎 Describe the bug

Getting this error when trying to complete issue with import Github

## 🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:

1) Import issue from public repo
2) No KYC, No whitelist etc
3) When confirm get this error

## 🔗  Screenshots

<img width="736" alt="Screenshot 2023-12-01 at 15 02 04" src="https://github.com/HeroesHQ/HEROES/assets/18598519/bb904247-b169-49d7-8663-f09055201c73">

**Comment by AngelBlock** [comment]
Please clear session and check again @Kisgus. That error not related to the GitHub import, it happened due to upgrade.
