### ISSUE TITLE
[WORK REQUEST] Move "Press Done" to same screen as "Claim",

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#139]
🤼‍♂️  **What problem is your work solving.**

Almost 50 % of users dont intutively find that they need to click on applicants to **press done** 

🎉  **Describe the work you'd like**

- [x] Include "Press done as option on bounty page

- [x] The easiest seems to be to remove Applicants page totally?

## 🔗   Work doc(s) / inspirational links

Example of user lost

<img width="818" alt="Screenshot 2023-12-08 at 14 13 20" src="https://github.com/HeroesHQ/HEROES/assets/18598519/dd94a314-7ae6-4d5b-becd-f01e3bd9b5de">

**Comment by maanemanden** [comment]
As simple as this?

<img width="972" alt="Screenshot 2023-12-11 at 16 31 00" src="https://github.com/HeroesHQ/HEROES/assets/24993369/156d1560-5b36-4a5b-9d91-21a6af176d80">

**Comment by Kisgus** [comment]
I think we should totally remove the "applicants" page and move all that is currently on this page to Bounty details page, more than 50 % of users do not understand that Applicants is a seperate page.

**Comment by maanemanden** [comment]
will provide asap

**Comment by maanemanden** [comment]
here you go all on one page :)  https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4873%3A5136&mode=design&t=nCtnAqaEGLLH0tni-1

**Comment by AngelBlock** [comment]
@maanemanden I don't see it in  Sigma ser.

**Comment by Kisgus** [comment]
When a hunter press "done", this button should not be under "applicants", but be at the exact same place as the "claim" button is, so not under "applicants" but under "Bounty Details"

**Comment by AngelBlock** [comment]
The existing design is confusing and insufficient, please suggest new design 
@Kisgus @maanemanden

**Comment by Kisgus** [comment]
Please provide suggested design here @maanemanden so we Can review asap

**Comment by AngelBlock** [comment]
![2024-01-23 12 53 28](https://github.com/HeroesHQ/HEROES/assets/80400686/e70bc79b-915e-43a8-877f-c8c1627be7bb)


 we are still looking for design of all the elements in the space and its possition

**Comment by cudam321** [comment]
made a prototype and small mockup based on Fred design here

prototype:https://www.figma.com/proto/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4522-10421&t=iEMKdupSlc9ccuI6-1&scaling=min-zoom&page-id=4446%3A1286&mode=design

mockup: https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4522-10421&mode=design&t=dVYjnDeZIC11k9Pg-0

**Comment by cudam321** [comment]
updated mockup for both hunter view and funder view
https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4446-1286&mode=design&t=dVYjnDeZIC11k9Pg-0
