### ISSUE TITLE
Add button to founder journey to finalise rejected, expired bounties 

### ISSUE THREAD

**Issue by AngelBlock** [HeroesHQ/HEROES#141]
Currently, bounties cannot be completed if there are applicants who have been rejected or whose applications have expired. 

Although the smart contract already allows for finalization and withdrawal, we need to add a button in the UI to facilitate this process.

**Comment by cudam321** [comment]
i thought there's already a button? "Update Bounty Status" when grace period ends? 

imo this should be automatically
