### ISSUE TITLE
[WORK REQUEST] NW NEWS Submission bounty on HEROES

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#144]
🤼‍♂️  **What problem is your work solving.**

Increase activity on Heroes, as well as implement more NEARWEEK processes with Heroes.

🎉  **Describe the work you'd like**

To move the news submission over to Heroes, we need a bounty that can:

- [x] Get submission from multriple Hunters
- [x] Get multriple submissions from the same Hunter for the same bounty at the same time
- [x] Multi approval of submissions
- [x] Can handle 200 submissions pr. bounty
- [x] A sorter that can show the approved submissions

Notes:
Basically we want to replace Sputnik/AstroDAO as our main service for news, and therefore need about the same functionalities as they have.
I imagine the flow to look like this:
1. In the start of the week a bounty is created
2. Contributors submit news during the week
3. That means they will have to make more claims before their previous claim is processed
4.  At the end of the week News are approved
5.  The rest of the NW content team then needs to be able to view the approved submissions# 🔗   Work doc(s) / inspirational links

**Comment by AngelBlock** [comment]
**UI/UX clarification required.** feel free to discuss over the call.

Should the same option be used for 144 "NEWS Submission", but here we need another option - "Claimer can create multiple claims simultaneously"?

Or should we create a "Add News" button somewhere, for example?

**Comment by Kisgus** [comment]
1) Both users should have acess to export all of their transactions on an account basis. Yes all fees should be included (like commission or tx fees). Bond should not be included.

**Comment by AngelBlock** [comment]
@fedencer @rostyslav-dzhuman

**Comment by Kisgus** [comment]
Not sure i follow how you mean with "same option as in 144". I imagine we put this on same settings list view as enable/disable auto-approval for starters. Can call it "recurring submissions"

**Comment by RasmusTheOnlyOne** [comment]
Feedback on One for all with Multiple Claimants:
Currently there is not an option for voting on multiple proposals at the same time.
