### ISSUE TITLE
[WORK REQUEST] HEREOES TELEGRAM BOT: Allow to submit news via Telegram bot

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#155]
🤼‍♂️  **What problem is your work solving.**

Allow to submit news to nearweek via Telegram

🎉  **Describe the work you'd like**

- [x] NEARWEEK bot is added to a Telegram group
- [x] A similiar command like !submit @nearweekbot on Twitter allows to submit news to NEARWEEK according to the same flow as for nearweek twitter bot

**Comment by Kisgus** [comment]
@eclipseeer Please help update this issue

**Comment by cudam321** [comment]
should also some kind of specification to prevent spam:
- only works with links from a certain platform: twitter, medium, substack etc...

**Comment by Kisgus** [comment]
Further specification based on first test @eclipseeer 


**Profile picture of bot:**

![yGqdQ6F0_400x400](https://github.com/HeroesHQ/HEROES/assets/18598519/53fefc25-5c76-44d3-819a-ef8647e9e91d)

**Description of bot**

I aggregate news related to 
[@NEARProtocol](https://twitter.com/NEARProtocol)
/
[@auroraisnear](https://twitter.com/auroraisnear)
. Submissions will be sent to the 
[@NEARWEEK](https://twitter.com/NEARWEEK)
 contributors who will redistribute if approved by the DAO! 🕸

**Channel to post in**

https://t.me/+UYhIYWxTWEkwYjhk

**Name of bot**

@nearweek_newsbot

**Command of bot**

nearweek_newsbot

/nearweek_newsbot  (if possible)

Or 

/submit @nearweek_newsbot

**Comment by eclipseeer** [comment]
@Kisgus the bot is ready, only need to get access to server, where bot will be hosted. @AngelBlock will help with it

**Comment by eclipseeer** [comment]
Bot name it https://t.me/nearweek_newsbot 
Command - /submit@nearweek_newsbot - when the user will reply to message with this command, the original message will be sent to the TG group and bot will thank user in the group, where the original message and the reply with command were posted.
