### ISSUE TITLE
[WORK REQUEST] Simplify "Descriptions, Details, Deadline" bounty creation screens

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#160]
🤼‍♂️  **What problem is your work solving.**

Remove stuff no longer relevant

🎉  **Describe the work you'd like**

- [ ] See mockups
- [ ] Simplify deadline step in line with #157 

## 🔗   Work doc(s) / inspirational links

Please add figma here @cudam321

**Comment by cudam321** [comment]
mockup is ready to work on
https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4338-1408&mode=design&t=zQWVxC0VDpOIJdcT-0
<img width="845" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/58fb26e3-36bf-4076-93f4-8ee4b4878640">

**Comment by Kisgus** [comment]
Ready to be assigned for frontend @AngelBlock
