### ISSUE TITLE
[WORK REQUEST] Merge "bounty details" screen with "applicants" screen

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#162]
🤼‍♂️  **What problem is your work solving.**

In accordance with #139, we need to make it easier for help to know where they have to take action, the applicants page is very hard for people to understand

🎉  **Describe the work you'd like**

- [ ] Merge the two
- [ ] Remove duplicate info as relevant

**Comment by cudam321** [comment]
Mockup is ready
https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=5141%3A1533&mode=design&t=zQWVxC0VDpOIJdcT-1
<img width="590" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/2d31032b-77ec-49e5-a8e0-1952c85cd2e2">

**Comment by Kisgus** [comment]
**Feedback:**

Size of pop-up:

Testing feedback, the pop-up is too squeezed, please see the sizing in the mock-ups. 

Text on pop-up:

The text is cut unnecessarily, so its not possible to see the full text, please adjust as in mockups



![Image](https://github.com/HeroesHQ/HEROES/assets/18598519/25cb42f4-82cd-49a3-af87-7a2afeb3507b)
