### ISSUE TITLE
Download invoice not working

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#164]
🔎 Describe the bug

Paid out bounty, cannot download invoice 

## 🤼‍♂️  To Reproduce

Steps to reproduce the behaviour:

https://heroes.build/bounties/bounty/350

Tx: https://nearblocks.io/txns/DGootGh8gNLuUKpFFzEhEWeiaqaR8W822xtaFE3k4y4X

<img width="1323" alt="Screenshot 2024-01-30 at 10 11 10" src="https://github.com/HeroesHQ/HEROES/assets/18598519/9929034b-a7f9-4ee3-b37b-3ac7fc6818f9">

<img width="695" alt="Screenshot 2024-01-30 at 10 11 03" src="https://github.com/HeroesHQ/HEROES/assets/18598519/62b0c353-0d0c-4e38-962b-d54e084cc80b">

## 🎉 Expected behaviour

Gotta receive invoice on email and be able to download it

**Comment by Rostyksv** [comment]
@Kisgus fixed, test please
