### ISSUE TITLE
Getting failure when trying to create bounty

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#165]
🔎 Describe the bug

Creating bounty get this error after having confirmed in wallet

<img width="1022" alt="Screenshot 2024-02-01 at 15 53 41" src="https://github.com/HeroesHQ/HEROES/assets/18598519/60aafccd-311d-43da-b215-590edc469889">

https://nearblocks.io/txns/EPoLWANrRCj1FHj8fywjgmau9Ap4EwZpWx2Vshs3k9Ds

## 🤼‍♂️  To Reproduce
Steps to reproduce the behaviour:

1) Setup bounty 
2) Confirm in wallet
3) Receive failure message

**Comment by AngelBlock** [comment]
@Kisgus 

In the bounty that is being attempted to create, there is no deadline (WithoutDeadline). This type of deadline cannot be combined with allow_deadline_stretch=true. This option should be disabled.

**Comment by AngelBlock** [comment]
The UI fix is considered

**Comment by Kisgus** [comment]
This issue was created using the duplicate feature, it has exact same settings as all other nearconhackathon bounties paid out before this, so if there is an issue with no deadline specified that's because you've pushed #157 ?

**Comment by AngelBlock** [comment]
@Kisgus #157 is work in progress and have not been pushed to any env.
