### ISSUE TITLE
[WORK REQUEST] Reduce 1 NEAR bond to 0.001 NEAR bond 

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#166]
🤼‍♂️  **What problem is your work solving.**

The bond is currently too a big friction point, we should make it smaller to make it less of an entrance barrier while still keeping it to still maintain a level of spam protection

🎉  **Describe the work you'd like**

- [x] Bond drastically reduced
- [x] Plan in place for him we suddenly encounter lots of spams - can we then easily make it bigger?

**Comment by AngelBlock** [comment]
Settings have been applied https://explorer.mainnet.near.org/transactions/BKdWWRvvqpVSY3DVmDV21vRfk7KB2xLUvPki9cR2EAWi

**Comment by AngelBlock** [comment]
confirmed and working

<img width="451" alt="Screenshot 2024-02-06 at 16 58 12" src="https://github.com/HeroesHQ/HEROES/assets/80400686/de76a4d0-ad1c-4454-8855-2d24ca80150c">
