### ISSUE TITLE
News Bounty V.2 for Design

### ISSUE THREAD

**Issue by RasmusTheOnlyOne** [HeroesHQ/HEROES#173]
Of the Original issue #144, these requrements were listed, and these have been completed:
 

- [x] Get submission from multriple Hunters 
- [x] Get multriple submissions from the same Hunter for the same bounty at the same time
- [ ] Multi approval of submissions (Technically done on the "Different Tasks" bounty version, but isn't showing on the "One For All" version)
- [x] Can handle 200 submissions pr. bounty
- [ ] A sorter that can show the approved submissions

First let's look at a more precise solution for "Multi approval", which now will be re-named to "Multi Vote". Currently the "Different task" version have this button:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/cefd0b9c-9203-497b-bfd4-9a5edca3382c)

Whereas the "One For All" version don't

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/addf5a2a-71a1-46af-9cef-c4d86cfb1a21)

To function optimally for the Funder, so they can actually process in volumes of the targeted 200 proposals, we need to minimize the need for the "NEAR Transaction Screen", as you now would be able to approve with one screen, but would need to process each Reject individually. 
To tackle this issue, I propose we do a "Process Buffer", which saves the Funders choice of "Approve" or "Reject", and send all the votes in simultaneously, so it only requires one long "NEAR Transaction Screen".

An example of this could look like this:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/b776ba7b-203e-4830-b158-1bc37cbc32c9)

Here the proposals choice gets added to the buffer, where a submit button can start the processing.

Here we can imagine how it would look like on the site:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/b40d73bb-f175-4c73-a857-2f63aad6452c)

------------------------------------------------------------------------------------------------------------------

For the sorter we need three boxes to be shows:

- [ ] Show Approved Proposals
- [ ] Show Rejectes Proposals
- [ ] Show Active Proposals
- [ ] Show All Proposals (Show no matter the status of the proposal)

*Multiple of these can be checked at the same time, to show both. They should sorted after the timestamp the were originally submitted on.

A proposal should only appear if their status matches that of one of the checked boxes, but "Show All" should be default, and will turn off when one of the other boxes turn on.

As of now the already processed proposals just show a blank field, but we need them to show if they have been approved or rejected:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/4af98255-8cb2-4ee2-9644-cf1674552776)

In the case of this image, if the only the "Show Active Proposals" was turned on, the blank proposals should be hidden, and the active proposals should take it's place, so to not leave holes.

Here is show how the "Show Boxes" could look like on the page:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/95219bcc-1f36-46dc-b020-a825cc6fc0a2)

---------------------------------------------------------------------------------------------------------

Bugs

When showing the "Chat" option for the proposals it currently looks like this:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/8ed72c04-3434-4cad-b444-95d8cdc30ff6)
*Taken in Edge browser on windows laptop

It seems like the Messages as well as the message input doesn't fit the frame, and we also want links to clickable in the messenger frame.

**Comment by cudam321** [comment]
Design is ready, please check carefully this prototype to understand the logic:
https://www.figma.com/proto/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=5634-6834&t=21TSEzDQ6jUqRTu9-1&scaling=min-zoom&page-id=5634%3A6350&mode=design

let me know if there is any questions

**Comment by Kisgus** [comment]
Its important to stress this feature needs to be available for ALL MULTI-TASKING bounties (not only bounties allowing participants to submit multiple claims"
