### ISSUE TITLE
Change/Improve wording in some sections to avoid confusion

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/heroes#19]
Change wording to "This applicant has not completed KYC verification"
<img width="300" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/c217d405-0896-4386-a3d6-a85c7248aff7">

Add "This bonus claim will require 1 NEAR deposit to prevent spam, this deposit will be returned after you complete or give up the bounty or the owner rejects your claimant."
<img width="300" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/ac69d7cc-dd67-4d3a-8d51-34d727ebfd65">

Change wording to "You have not completed KYC verification. Please complete your KYC to continue"
<img width="300" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/46704692-1616-4555-a4b2-f79649f9855d">

Change wording to "You are about to approve this Hero's work for your bounty and agree to release the reward!"
<img width="300" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/b35f1a7a-ef08-4884-9772-4461526fbf7f">

**Comment by cudam321** [comment]
Change wording to "Use HEROES' KYC Verification, only applicants who passed HEROES' KYC can apply and work on this bounty!

_This cannot be changed once the bounty is live!_"

<img width="508" alt="image" src="https://github.com/HeroesHQ/heroes/assets/97611620/b4805873-67c3-490f-9a4d-23342aded42a">

**Comment by rostyslav-dzhuman** [comment]
Done. Please check.

**Comment by Kisgus** [comment]
@cudam321 please review

**Comment by rostyslav-dzhuman** [comment]
![image](https://github.com/HeroesHQ/heroes/assets/89782935/3981249e-d969-4eb0-bc2b-1ff1227ba1e5)
Please check on prod.

**Comment by cudam321** [comment]
thank you! @rostyslav-dzhuman
