### ISSUE TITLE
RE:ADD TOKEN REQUEST-$NVIDIA

### ISSUE THREAD

**Issue by OxRage** [HeroesHQ/HEROES#194]
**What is the ticker requested**
$NVIDIA

**What is the token contract**
nearnvidia.near

**Comment by AngelBlock** [comment]
Approved by @Kisgus 

Token added: https://explorer.mainnet.near.org/transactions/DykokibM6xpweuMQeU2npLZFrhB25aaMSLY5WsH3qaEm
