### ISSUE TITLE
Auto approve Hunter for multiple claims

### ISSUE THREAD

**Issue by RasmusTheOnlyOne** [HeroesHQ/HEROES#198]
When a hunter have already been approved for a bounty, and wants submit another submission, they should already be approved, and don't need to apply first before submitting each submission. This take an extra click + loading time for each.

- [ ] Make it so that if a Hunter have already been approved and submitted once, they don't need to apply again

*Note: This also applies for the auto-approval function, as you also need to apply for each submission with that.

**Comment by RasmusTheOnlyOne** [comment]
@cudam321, I could use some help with putting in a "Submit" button in instead of the current "Apply" button, when a Hunter have already been approved and submitted

**Comment by Kisgus** [comment]
@heroesbot 200 usdc deadline: 1/15
