### ISSUE TITLE
Profile Picture & Select time on HEROES Widget

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#2]
**Update profile picture **

- Can we include near.social profile picture properly?

**Options to select time**

- Allow user to select longer times?
- Is it possible to not have select a time?

<img width="1172" alt="Screenshot 2023-05-15 at 14 03 12" src="https://github.com/HeroesHQ/heroes/assets/18598519/6108cd8b-1a80-48d8-b40f-b8679963a4e8">

**Comment by AngelBlock** [comment]
Please refrain from testing near.org widget, its not finished yet.
