### ISSUE TITLE
New source for the Live News Wire

### ISSUE THREAD

**Issue by RasmusTheOnlyOne** [HeroesHQ/HEROES#223]
Currently we have a "Live News Feed", which gets the data from the News DAO: nearweek-news-contribution.sputnik-dao.near (I'm not sure which DAO page it gets it from, but it's that DAO)
We want to avoid using the DAO, and would rather have it in a google sheet, where the News Feed listens to a column, that updates automatically (every five minutes or so). How easy would this be to change?

Here is where the current Live Feed is displayed:

![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/b0e14e92-7b7a-42e7-b598-d249fb3b7d7f)

**Comment by rostyslav-dzhuman** [comment]
Could you provide access to the google sheet with links, please?
