### ISSUE TITLE
Profile Bio information - What is public, what is not?

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [HeroesHQ/heroes#23]
**Is your feature request related to a problem? Please describe.**
As a user I don't know if the information I post in my profile bio is available to public. I want to know specifically what information is publicly available and featured on my HEROES profile page and what isn't.

**Describe the solution you'd like**
When setting up profile page, please indicate clearly which fields on the profile page are available for public to see.

**Additional context**
![Screenshot 2023-06-16 at 11 05 18](https://github.com/HeroesHQ/heroes/assets/89806831/94383f4d-5806-4486-8cea-0c0c2c34455d)

**Comment by Kisgus** [comment]
Please check by going to a public profile @P3ter-NEARWEEK, by clicking on the user you can view it

**Comment by Kisgus** [comment]
One suggestion could be that we indicate with text what is public and what is not and we share a link you can click on to view it? @P3ter-NEARWEEK @cudam321 ?
