### ISSUE TITLE
[WORK REQUEST] Final v1 sign-up, login & edit profile

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#233]
🤼‍♂️  **What problem is your work solving.**

Reduce unnecessary friction steps for login in

🎉  **Describe the work you'd like**

- [x] Login with Github & Google
- [x] Less input as discussed

## 🔗   Work doc(s) / inspirational links

Feature list

https://docs.google.com/document/d/196wsXOsv00HoITnv-zF3OGlnvBWNsHbCq_YWNEbOmWY/edit

**Comment by cudam321** [comment]
Design is done
https://www.figma.com/design/kqZ5FzeLV1WBAERZCngbFC/Heroes?node-id=6377-8&t=CGt4GaPQZ4LbYCfG-1
