### ISSUE TITLE
[WORK REQUEST] Export transactions & invoices end-to-end

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#235]
🤼‍♂️  **What problem is your work solving.**

Remove dedicated sidebar pages for transactions & invoices

🎉  **Describe the work you'd like**

- [x] Include on same page, do not offer different transaction options (export sheet with all types with each type in a subsheet)

## 🔗   Work doc(s) / inspirational links

https://docs.google.com/document/d/196wsXOsv00HoITnv-zF3OGlnvBWNsHbCq_YWNEbOmWY/edit

**Comment by cudam321** [comment]
Design is ready
<img width="518" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/963e9bd7-47d4-4d4c-960d-2f837800cfcc">
