### ISSUE TITLE
Edit profile functionality

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [HeroesHQ/heroes#24]
**Is your feature request related to a problem? Please describe.**
When a user clicks the "edit profile" tab, the profile picture and banner picture is not saved.

**Describe the solution you'd like**
I would like this information to be automatically stored so I easily can edit bio info and not have to add images again.

**Additional context**
![Screenshot 2023-06-16 at 11 15 37](https://github.com/HeroesHQ/heroes/assets/89806831/657dc6f2-4a67-4202-a555-158ff89394a0)

![Screenshot 2023-06-16 at 11 18 33](https://github.com/HeroesHQ/heroes/assets/89806831/a14d5e09-99f1-4937-8d50-6962debf50e1)

**Comment by Kisgus** [comment]
Please check now @P3ter-NEARWEEK if this is still not working, it should be fixed now.

**Comment by P3ter-NEARWEEK** [comment]
I've previously ticked the "remember me" box when logging in, and when clicking the profile button I get the code message, however I don't receive any code in my email. I've hit the re-send button but still don't receive a code. Also tried clearing my cookies, same result.

![Screenshot 2023-06-23 at 09 48 01](https://github.com/HeroesHQ/heroes/assets/89806831/e9119e95-3a13-46aa-b9b8-2e1f9b3ce506)
