### ISSUE TITLE
Return email error if email doesent exist when a user signs up (email doesent exist)

### ISSUE THREAD

**Issue by maanemanden** [HeroesHQ/heroes#25]
we should tjeck emails in backend and return a error message (typos in email, prevent bots etc)

**Comment by Roh4n-1729** [comment]
Hey! if you are working with Nodejs REST API I can try and fix the issue.

**Comment by Kisgus** [comment]
Assigning @AngelBlock to research our options and evaluate if this is a priority right now.

Hey @Roh4n-1729 thanks for your offer, but in this case our core team will take care of it :) Are you looking for other small developer tasks? Then we are happy to put up a bounty for you. Which type of stack are you looking for?

**Comment by Roh4n-1729** [comment]
Sure!! I am up for it. I know MERN stack so looking for those tech stacks. I haven't done it yet, though doing it now. Thanks!!
