### ISSUE TITLE
Search in top menu not responding - Chrome

### ISSUE THREAD

**Issue by maanemanden** [HeroesHQ/heroes#27]
<img width="1306" alt="Screenshot 2023-06-19 at 21 45 56" src="https://github.com/HeroesHQ/heroes/assets/24993369/916c6a3d-a64b-49d5-9e90-2ced8957aea1">

**Comment by Kisgus** [comment]
Hey @maanemanden thanks for creating this, what should it return? And in which format?? Is it bounites, profiles or both?

**Comment by maanemanden** [comment]
See https://www.upwork.com/ for reference

**Comment by Kisgus** [comment]
it seems upwork only shows people when searching, is that what you propose? @maanemanden
