### ISSUE TITLE
Make list more responsive with color

### ISSUE THREAD

**Issue by maanemanden** [HeroesHQ/heroes#28]
<img width="987" alt="Screenshot 2023-06-19 at 22 46 23" src="https://github.com/HeroesHQ/heroes/assets/24993369/b77b979b-3770-43fe-9ab4-4da81b9e9dd3">

**Comment by Kisgus** [comment]
Hey @rostyslav-dzhuman, the purpose of this issue is to make the selected skills under profile page a yellow color when selected, please see figma for the color code.

**Comment by rostyslav-dzhuman** [comment]
Done. Please check.
