### ISSUE TITLE
Not able to finalize claim bounty

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#3]
On google chrome / macbook, it keeps loading and no wallet pop up is activated. The account is not ledger secured.

<img width="1460" alt="Screenshot 2023-05-15 at 14 10 20" src="https://github.com/HeroesHQ/heroes/assets/18598519/9d800ba9-ae0a-41fd-ab82-9a8c682983be">

**Comment by AngelBlock** [comment]
Please refrain from testing near.org widget, its not finished yet.
