### ISSUE TITLE
Remove import from Gitcoin 

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#37]
## 🎉   Subtasks

- [ ] Change titel to "Import from Github" 

<img width="566" alt="Screenshot 2023-11-02 at 16 40 17" src="https://github.com/HeroesHQ/Kanban/assets/18598519/e58a69c4-947c-4e00-a1fc-0d64589bc2e0">

- [ ] Remove Gitcoin field

<img width="582" alt="Screenshot 2023-11-02 at 16 45 57" src="https://github.com/HeroesHQ/Kanban/assets/18598519/0a017889-ecda-47cc-8e73-e234bcf8afa1">

**Comment by Kisgus** [comment]
Thanks works, please deploy to production @rostyslav-dzhuman

**Comment by AngelBlock** [comment]
@Kisgus on prod
