### ISSUE TITLE
Loading time on heroes UI very slow

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#4]
## Issue

After I have setup a bounty I have no response for more than a minute within UI, I also have no message or notification around this.

## Proposed solution

- Optimize load time so that it works as fast as on near.discovery widget 

and / or

- Provide text and email response to the bounty creator

**Comment by AngelBlock** [comment]
@Kisgus please test. on staging.

**Comment by Kisgus** [comment]
tested with 2 issues now, it's almost instant, gj!
