### ISSUE TITLE
Add unsubscribe link to emails 

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#44]
Currently it's impossible to unsubscribe from HEROES emails, which will cause people to mark them as spam. Add an "unsubscribe" link to the email footer.

**Comment by starpause** [comment]
Stand up discussion: we might not want to have "unsubscribe". Need a more detailed ticket around this that specifies the different kinds of email and what gets toggled off and on when someone visits "unsubscribe" link.

**Comment by Rostyksv** [comment]
> Stand up discussion: we might not want to have "unsubscribe". Need a more detailed ticket around this that specifies the different kinds of email and what gets toggled off and on when someone visits "unsubscribe" link.

okay, waiting for details
