### ISSUE TITLE
Too many bounty pages to fit on screen on iPhone 12 iOS

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#45]
## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️  Reviewer

@

## 🔗   Work doc(s) / inspirational links

![image](https://github.com/HeroesHQ/Kanban/assets/18598519/7c9df583-7a3d-49e0-b05d-dd6b80169230)

**Comment by cudam321** [comment]
ready to push to prod

**Comment by cudam321** [comment]
![Screenshot_20231128_205940_Samsung Internet.jpg](https://github.com/HeroesHQ/HEROES/assets/97611620/0e55f756-817f-47ca-abb6-a31ed1edb179)
