### ISSUE TITLE
Make Github import / link optional and turn it into a generalised "import section"

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#5]
## Issue

It's a blogger for non-coders that Gitcoin is currently mandatory. It's also an issue even if you are using Github that you do not know as a bounty creator that you need to have your Github issue set up.

## Motivation

**Quick fix**: make it optional 

**Design midterm fix**: Make a generalised import section

**Comment by AngelBlock** [comment]
fixed by switching new bounty / import tabs
