### ISSUE TITLE
Clone/Duplicate/Copy Bounty

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#50]
As a funder I created a bounty: https://heroes.build/bounties/bounty/137 and need to make 7 more similar bounties. To make things easier on me I'd like a clone button to fill out the bounty for me and let me review it to change anything that needs changing.

Duplicate icon here?

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/2682a7d8-a097-49e4-8988-17173e0964ae)

**Comment by starpause** [comment]
@Rostyksv update?

**Comment by Rostyksv** [comment]
@starpause It's done, but needs to be deployed (I don't have access to deployment, so i'll write here when it will be done).

**Comment by Rostyksv** [comment]
@starpause now on test

**Comment by cudam321** [comment]
works for me, it copies everything from basic metadata to multitasking settings
<img width="300" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/4caad41e-a6fa-49b2-9e9e-63eb7ccba97d">
<img width="300" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/dace276f-ebb6-417d-b267-25dd704b5206">

@starpause have you thought about the suggestion what i told you about around "Import past bounties" vs this clone bounty feature? i guess both can run in parallel 

another thing, via testing this today i also came with another thought that when i visit a bounty, i'm looking to take actions on the bounty & cloning isn't an action that have an actual impact on the bounty. Was curious what do you think about keeping the bounty details page with only actions that can impact status of the bounty & keep everything related to bounty creation inside the "create bounty" flow

**Comment by starpause** [comment]
@cudam321 "import past bounties" as you described does make sense. can you create it as a separate work request issue? we will need wireframes and design for that journey.

@Rostyksv looks good to push, thanks for the quick fix.
