### ISSUE TITLE
Apply Search to "Your Bounties"

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#51]
### Developer Direction

Apply Search to both "Browse Bounties" and "Your Bounties".

### Journey

As a funder, after I create a bounty I want to share it.

### Issue

It's hard to find a bounty after I create it. Going to the bounties page doesn't show the bounty, which makes me think that it didn't actually get published/posted.

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/d04c0253-b7ac-4d90-be1a-ad598e2c9a65)

If I go under "Your Bounties" I can find it: 

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/fbafd4ce-7655-423a-8b24-dbc2bf2385ce)

### Implementation Idea

Display all active bounties, including ones I created, on this page https://heroes.build/bounties

**Comment by starpause** [comment]
@Rostyksv please push to stage/production

**Comment by rostyslav-dzhuman** [comment]
This issue is related to https://github.com/HeroesHQ/HEROES/issues/55. Please check it comprehensively before deploying to prod.

**Comment by starpause** [comment]
#55 looking good on test so this can be pushed along with it.

**Comment by starpause** [comment]
under windows 11 chrome latest:

here is search working for me inside of "your bounties"

![TsuSN5aIG1](https://github.com/HeroesHQ/HEROES/assets/408953/1a2e1a4f-f79b-466a-a094-d39be8672bfa)

here is search working for me at the "browse bounties" level

![8ijPoLkqKT](https://github.com/HeroesHQ/HEROES/assets/408953/256e34c8-f452-4ff6-8feb-543cfa924050)

is it possible in your screenshot that a search term is in the text of the bounty rather than the title?
