### ISSUE TITLE
Visit User Profile From Bounty Applicants

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#53]
## Journey

As a funder I have received an application for my bounty. I want to check on the profile of the applicant to help me decide if I'll accept the applicant or not.

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/b8f8f71a-77e1-4350-a371-b0113b33cfb4)

## Issue

Can't click on the applicant's name to view their profile. 

## Implementation Idea

I would expect clicking on the profile to take me to https://heroes.build/user-info/_________

**Comment by rostyslav-dzhuman** [comment]
This feature is implemented; profile viewing is available for applicants who have completed the user profile.
