### ISSUE TITLE
Setup Near.Social **Gateway**

### ISSUE THREAD

**Issue by AngelBlock** [HeroesHQ/HEROES#54]
NEARWEEK components are slow with suggested workaround with iFrame.

- [ ] research available gateways 
- [ ] prepare own gateway
- [ ] deploy gateway 
- [ ] consider using own smart contract YES/**NO**
- [ ] move NEARWEEK to own gateway
- [ ] setup DNS
- [ ] QA

**Comment by Kisgus** [comment]
No longer a priority
