### ISSUE TITLE
Deep Link Into Filtered View of Bounties

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#55]
![Image](https://github.com/HeroesHQ/Kanban/assets/408953/1fa3fd2d-96a4-449b-acc7-4c63f5c2e09f)

Deep link into filtered view of bounties. For example 

`https://heroes.build/bounties?f=blockchain` would only show bounties with the `blockchain` tag.

This issue is only for deep linking to tags, not category/experience/conditions.

Ideally we could link to multiple tags but linking to a single tag fulfils the user journey.

**Comment by rostyslav-dzhuman** [comment]
Try this https://test.heroes.build/bounties?tags=NEARCON2023

**Comment by starpause** [comment]
@rostyslav-dzhuman https://test.heroes.build/bounties?tags=NEARCON2023 did work, thanks! can we make the deep links not case sensitive so that https://test.heroes.build/bounties?tags=nearcon2023 also works?

**Comment by rostyslav-dzhuman** [comment]
Updated, filters ignore case sensitivity. Please check.

**Comment by starpause** [comment]
Looks good on test, good to push to stage/production.
