### ISSUE TITLE
Validate Funder Contact Text Input

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#59]
## Journey / Context 

Fiona 🐤💰 wants to list a new bounty.

## Issue

Funder contact information is not validated. 

![Image](https://user-images.githubusercontent.com/408953/278511708-95326364-719f-47e7-af3d-e263b2259c30.png)

## Implementation Idea

Use regex to ensure the input is a valid email or url.

**Comment by cudam321** [comment]
looks good to me
<img width="504" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/0779f47b-2ed8-4480-af05-219b77a49c79">

i guess it's overkill for now to validate input for twitter, discord & telegram

**Comment by starpause** [comment]
We are taking contact out of the bounty creation flow and keeping it on the user profile update flow, so we don't need to validate here. It will be good to have validation when users are filling out their contact channels on their profiles so the work in this request will still be valuable.

**Comment by RasmusTheOnlyOne** [comment]
Work Good
