### ISSUE TITLE
Can't Click On Connect Wallet Button

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#61]
## Journey / Reproduce

I had my wallet connected & logged out & logged back in & then I got a notification to connect my wallet.

## Issue

I can't click the button in the alert or in the menu.

![Image](https://user-images.githubusercontent.com/408953/278516094-50309464-5c02-412d-bcbd-0e5e1caa8cb1.png)

## Work Around

Hard refresh of the browser allows me to click the button. Doing the same journey reproduces the issue for me. Using Chrome in Windows.

**Comment by Kisgus** [comment]
@starpause @AngelBlock still an issue?

**Comment by starpause** [comment]
I'm able to click on the buttons now but I'm not sure why I get prompted to connect my wallet after I log out and log in. Is that user flow intentional or is it a bug?
