### ISSUE TITLE
Forgot Password Is Not Sending Email

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#66]
After entering email on this screen:

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/da987374-132f-499a-988f-d72a1f6aed93)

User does not receive an email to reset their password. They checked spam.

**Comment by AngelBlock** [comment]
@starpause Please always specify environment: testnet/staging/prod

I can't replicate it on prod. 

please test and check spam folder.

**Comment by AngelBlock** [comment]
@starpause we are using ZeptoMail service

**Comment by starpause** [comment]
Can no longer reproduce, it must have been a temporary service hiccup.
