### ISSUE TITLE
Invoice feedback

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#7]
##  Remove "Address line 2" section, currently it says optional but its mandatory

![IMAGE 2023-05-16 10:20:54](https://github.com/HeroesHQ/heroes/assets/18598519/9c06995d-8b64-47ae-8e2d-088edba67ddf)

![IMAGE 2023-05-16 10:20:53](https://github.com/HeroesHQ/heroes/assets/18598519/ba772cf0-4e2b-45db-ae0b-d6f1938de1db)

**Comment by Kisgus** [comment]
Also it seems I need to deposit funds to just create an account? Is that correct @AngelBlock ?

**Comment by AngelBlock** [comment]
fixed
