### ISSUE TITLE
Sign-up with Github not existing

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#70]
## 🎉   Subtasks

- [ ] Add Sign Up with Github so that it works similiar to Sign In with Github now, this includes fetching username, email and profile picture.

##Sign-up now

<img width="757" alt="Screenshot 2023-10-30 at 16 10 32" src="https://github.com/HeroesHQ/Kanban/assets/18598519/358ebce4-a34a-43e8-9b0f-588e545dd1c8">

## Sign-in Now 

<img width="660" alt="Screenshot 2023-10-30 at 16 10 29" src="https://github.com/HeroesHQ/Kanban/assets/18598519/4a0e338a-1905-4827-9502-fba63dd90ab9">

**Comment by cudam321** [comment]
looks good on test
<img width="630" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/05f24c56-0325-4b2d-8430-48460a68c23e">
