### ISSUE TITLE
Add CTA To Email Notifications

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#71]
Include name of bounty and link to it in the notification email. 

"Activity to your bounty" should be a URL. Any time a "bounty" is mentioned make that a link to the bounty.

Include new buttons in emails:

Hunter CTA: Submit Work
Funder CTA: Share Bounty

List of Emails we send from [Email.js](https://github.com/HeroesHQ/heroes-api/blob/5bb74bc954561f9d617cb5bd7f43cf674c0a1ba0/models/Email.js#L14):

        'Welcome', 'FirstBountyPosted', 'YourApplicationForBountyAccepted',
        'WorkHasStartedOnYourBounty', 'BountyReadyForReview', 'BountySuccessfullyCompleted',
        'BountyOwnerRepliedInChat', 'WorkOnBountyAccepted', 'BountyNearingDeadline',
        'ActivityOnBountyAwaitsYourResponse', 'DecisionOnClaimBounty'

References: [Email templates to update](https://github.com/HeroesHQ/heroes-api/tree/5bb74bc954561f9d617cb5bd7f43cf674c0a1ba0/templates/emails), HeroesHQ/HEROES#100 original issue

**Comment by Kisgus** [comment]
https://docs.google.com/spreadsheets/d/1fiw1trDOsOrBaQmQ9s3xMlRJY87JvnZmtr3LW49bMYg/edit#gid=0
