### ISSUE TITLE
Support Native USDC Token

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#73]
Contract: https://nearblocks.io/address/17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1

**Comment by starpause** [comment]
@AngelBlock I don't see the option for native USDC in the drop down (only USDC.e) 

![image](https://github.com/HeroesHQ/HEROES/assets/408953/fc0b7a62-603b-4c42-b90a-0e47ee6f4867)

![image](https://github.com/HeroesHQ/HEROES/assets/408953/cab7f5f0-b5c5-40f5-81a6-ddce5415df90)

**Comment by starpause** [comment]
Currently enabled only for post pay bounties, needs to be for regular bounties as well.

**Comment by starpause** [comment]
let's label it `USDC (Native)`

**Comment by AngelBlock** [comment]
Token added to Prod, please test @starpause

**Comment by AngelBlock** [comment]
We do not support labels of pre-paid bounty tokens, if this is desirable please open separate HEP (HEOES Enhancement Proposals)

**Comment by starpause** [comment]
Tested USDC end to end on production https://heroes.build/bounties/bounty/194
