### ISSUE TITLE
gitbook

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#75]
- [ ] tutorials
- [x] [bounty types](https://heroes.build/bounties/bounty/139)
- [ ] past blog content
- [ ] changelog
- [x] [funder journey](https://heroes.build/bounties/bounty/137)
- [x] [hunter journey](https://heroes.build/bounties/bounty/138)
- no xrep
- [x] links on heroes.build to gitbook

old nearweek task this can close out: https://github.com/NEARWEEK/CORE/issues/1086

**Comment by Kisgus** [comment]
consider v1 done, ty
