### ISSUE TITLE
Land on Sign In page after Log Out

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#79]
after user logs out

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/d4efe857-4b71-4712-9025-a3edf7b2e5f2)

redirect them to login 

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/3c1c9643-a141-4922-9173-0dc0e02ecfd7)

**Comment by RasmusTheOnlyOne** [comment]
Still not landing on sign page. This is what we want shown after a user logs out:


![Image](https://github.com/HeroesHQ/HEROES/assets/92510030/2e1808fc-5f41-4358-9d54-0b325e77365e)

**Comment by Rostyksv** [comment]
> Still not landing on sign page. This is what we want shown after a user logs out:
> 
> ![Image](https://private-user-images.githubusercontent.com/92510030/290870963-2e1808fc-5f41-4358-9d54-0b325e77365e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjI5MjAsIm5iZiI6MTcwMjY2MjYyMCwicGF0aCI6Ii85MjUxMDAzMC8yOTA4NzA5NjMtMmUxODA4ZmMtNWY0MS00MzU4LTlkNTQtMGIzMjVlNzczNjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3NTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZjRjYjVhNGZjZTU2OWYwYjlhNGJiM2RlMDgxYTk2MThlNzM1OTg2OTIzM2MyYjI5Y2U5ZDU4ZTU1MjA2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TbcOCQeCERkza-iRMjRLqi_1-klsEE77jDZ4Sxo1dtk)

https://github.com/HeroesHQ/HEROES/assets/72131815/f11272d7-7948-425c-a12b-cf3975e92b64

i tried many times and it works for me, redirect to sign-in
