### ISSUE TITLE
Remove "Submit Bounty as a DAO" Option (Not Working)

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#84]
**Note for developer: Current direction is to remove the option to submit bounty as DAO for now as it is not functioning**

Funder gets this error in wallet

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/26d8828c-2092-4599-8b69-31532591f686)

And this error is displayed after hitting "Cancel" in wallet

![Image](https://github.com/HeroesHQ/Kanban/assets/408953/796546f6-c232-409f-9a83-1a61a159467d)

Can we display a more helpful message? Suggestion:

Your account {{WALLET_HERE}} does not have permission to create proposals on {{DAO_HERE}}. Would you like to submit your bounty as an individual NEAR account?

(Yes)(No)

*Yes button is primary, adjusts the bounty variable and sends the transaction to wallet again, No button dismisses error overlay.*

**Comment by starpause** [comment]
Looks good on test, please push to production @rostyslav-dzhuman @AngelBlock

**Comment by Kisgus** [comment]
I still see it on test @starpause @rostyslav-dzhuman ?

![Uploading Screenshot 2023-11-20 at 17.46.36.png…]()

**Comment by AngelBlock** [comment]
@starpause please test on prod

**Comment by starpause** [comment]
LGTM TY!
