### ISSUE TITLE
Hunter Profile listing page

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#87]
For example 
- https://metagame.wtf/players
- https://app.dework.xyz/contributors

Primary goal: give funders confidence in the number and quality of hunters on heroes. 

Secondary goal: allow funders to find hunters they want to whitelist for opportunities.

**Comment by Kisgus** [comment]
Feedback from @cudam321 

hey just had a quick look:
- looks like it is not indexing completed bounties? all profiles have 0 completed bounties
- also on the initial design, the skills of hunters should be displayed also. i dont see them here.

**Comment by Kisgus** [comment]
Feedback:

- Default view should show profiles with completed bounties (not sure what indexing is now)

- Github icon needs to be static in the buttom and not move

![Image](https://github.com/HeroesHQ/HEROES/assets/18598519/c2d8fc45-192d-4835-925f-feb554e8585e)

- When clicking completed bounties link to each completed bounty

![Image](https://github.com/HeroesHQ/HEROES/assets/18598519/d861272d-1fb9-4485-b212-fac60ff0a872)

**Comment by Kisgus** [comment]
**Question:** What is the difference in labels tracked here?



![Image](https://github.com/HeroesHQ/HEROES/assets/18598519/28f7b420-8d33-4ed2-9936-dc1279bb318f)



![Image](https://github.com/HeroesHQ/HEROES/assets/18598519/91a2a196-e66d-44f0-9af6-70b260411aef)

**Comment by maanemanden** [comment]
i have made some small adjustments to create a more clean view if there is empty states in the different profiles: [
<img width="688" alt="Screenshot 2024-01-16 at 22 31 15" src="https://github.com/HeroesHQ/HEROES/assets/24993369/b52ff021-6617-4799-b213-8b675cd82e07">
](url) find them here: https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4028%3A238&mode=design&t=EfrZM9X0drxklTlz-1
