### ISSUE TITLE
Cancel bounty still hangs around

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/heroes#9]
<img width="1292" alt="Screenshot 2023-05-19 at 11 18 26" src="https://github.com/HeroesHQ/heroes/assets/18598519/60b4af8c-144b-4fee-a88f-f35fbdf2a1ee">

<img width="989" alt="Screenshot 2023-05-19 at 11 21 23" src="https://github.com/HeroesHQ/heroes/assets/18598519/325677c7-4dbf-4a6e-8636-67d86b036afb">

Can ask Denys from tx explorer details

**Comment by AngelBlock** [comment]
this was improved, please test @Kisgus
