### ISSUE TITLE
Bounties color tag is bugged on mobile

### ISSUE THREAD

**Issue by cudam321** [HeroesHQ/HEROES#92]
**Describe the bug**
Color tags don't display properly on the browse page on mobile

**To Reproduce**
- Open heroes.build on mobile

**Expected behavior**
Tags not display in correct size

**Screenshots**
![telegram-cloud-photo-size-4-5958788123133591765-y](https://github.com/HeroesHQ/HEROES/assets/97611620/f3b8bcc0-0e64-48b6-a8a8-1264405a9a27)

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android 14
 - Browser: Samsung internet

**Additional context**
no

**Comment by AngelBlock** [comment]
![IMG_8289](https://github.com/HeroesHQ/HEROES/assets/80400686/7c5bef59-b3d7-49fd-bc04-c10f4e53b711)

**Comment by AngelBlock** [comment]
@maanemanden perhaps we need some design suggestions here ser
@starpause @cudam321

**Comment by RasmusTheOnlyOne** [comment]
Looks good on my android!

**Comment by RasmusTheOnlyOne** [comment]
Also good for me!
