### ISSUE TITLE
Show bounties progress in the top instead of the buttom

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#95]
<img width="1085" alt="Screenshot 2023-11-17 at 15 42 10" src="https://github.com/HeroesHQ/HEROES/assets/18598519/fe3834d1-42f1-4187-b0d0-a137df9fb96c">

From:

https://heroes.build/bounties/my

Order should be:

a) Bounties in progress
b) Bounty completed
c) Bounty cancelled

**Comment by Kisgus** [comment]
Test bot ser

**Comment by Kisgus** [comment]
Test bot ser

**Comment by cudam321** [comment]
ready to push to prod!
<img width="1920" alt="image" src="https://github.com/HeroesHQ/HEROES/assets/97611620/1da190ca-100e-4c1a-abb6-96e60bb6d65a">
