### ISSUE TITLE
Funder: Export CSV File of Transactions For Compliant Accounting

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [HeroesHQ/HEROES#98]
As a user I want all the information needed for compliant accounting when exporting my transactions. Format should be .csv or Excel format.,

## 🎉   Subtasks

- [x] Outgoing crypto tx overview
![Screenshot 2023-09-06 at 11 21 54](https://github.com/HeroesHQ/Kanban/assets/89806831/f28156c1-47b4-44f7-83b1-d5c5bdc61391)

- [x] Ingoing crypto tx overview (cancelled bounties that return to wallet and ingoing payments from bounties taken
![Screenshot 2023-09-06 at 11 21 54](https://github.com/HeroesHQ/Kanban/assets/89806831/da1ffb93-cba4-4248-8d75-32b9c645b381)

## 🤼‍♂️  Reviewer

@AngelBlock

**Comment by Kisgus** [comment]
Question from Denys:

Please clarify which of two should be visible to:
- founder
- hunter


Should TX fees, bond, etc be included in the reports?

**Comment by Kisgus** [comment]
A) Both users should have acess to export all of their transactions on an account basis. 

B) Yes all fees should be included (like commission or tx fees). Bond should not be included.

**Comment by Kisgus** [comment]
https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4510-3877&mode=design&t=0jhhU2bqWw2Boouc-0

**Comment by Kisgus** [comment]
This issue works as expected on test now @AngelBlock and it can be deployed now to mainnet. Be aware that we will have more updates regarding this with https://github.com/HeroesHQ/HEROES/issues/161
